[phases.setup]
aptPkgs = [
    "tesseract-ocr",
    "tesseract-ocr-eng",
    "poppler-utils",
    "libgl1",
    "libglib2.0-0"
]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
