from __future__ import annotations

from datetime import datetime
from io import BytesIO
from typing import Any

import pytz

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from reportlab.pdfgen import canvas

IST = pytz.timezone("Asia/Kolkata")


class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states: list[dict[str, Any]] = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_footer(total_pages)
            super().showPage()
        super().save()

    def _draw_footer(self, page_count: int):
        footer = f"Generated by BidScrutiny AI Engine | Page {self._pageNumber} of {page_count}"
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.grey)
        self.drawCentredString(A4[0] / 2, 10 * mm, footer)


def _to_str_list(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(item) for item in value]
    return [str(value)]


def _extract_vendors(analysis_result: dict[str, Any]) -> list[dict[str, Any]]:
    candidates = [
        analysis_result.get("bids"),
        analysis_result.get("vendors"),
        analysis_result.get("rankings"),
    ]
    for candidate in candidates:
        if isinstance(candidate, list):
            return [item for item in candidate if isinstance(item, dict)]
    return []


def generate_pdf_report(tender_id: str, analysis_result: dict, audit_logs: list) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        leftMargin=15 * mm,
        rightMargin=15 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        spaceAfter=6,
    )
    subtitle_style = ParagraphStyle(
        "SubtitleStyle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        textColor=colors.grey,
        spaceAfter=2,
    )
    section_style = ParagraphStyle(
        "SectionStyle",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=12,
        textColor=colors.HexColor("#0B4F8A"),
        spaceBefore=10,
        spaceAfter=6,
    )
    normal_style = styles["Normal"]

    now_ist = datetime.now(IST)
    analysis_date = analysis_result.get("analysis_date") or now_ist.strftime("%Y-%m-%d %H:%M:%S %Z")
    vendors = _extract_vendors(analysis_result)

    story = []

    # Header
    story.append(Paragraph("BidScrutiny — Procurement Analysis Report", title_style))
    story.append(Paragraph("Government of India | Confidential", subtitle_style))
    story.append(Paragraph(f"Report generated: {now_ist.strftime('%Y-%m-%d %H:%M:%S %Z')}", subtitle_style))
    story.append(Spacer(1, 8))

    # Section 1 - Tender Summary
    story.append(Paragraph("Section 1 — Tender Summary", section_style))
    story.append(Paragraph(f"Tender ID: {tender_id}", normal_style))
    story.append(Paragraph(f"Total vendors analyzed: {len(vendors)}", normal_style))
    story.append(Paragraph(f"Analysis date: {analysis_date}", normal_style))
    story.append(Spacer(1, 8))

    # Section 2 - Vendor Rankings Table
    story.append(Paragraph("Section 2 — Vendor Rankings Table", section_style))
    rankings_data = [["Rank", "Vendor Name", "Compliance Score", "Status (Compliant / Rejected)"]]

    sorted_vendors = sorted(
        vendors,
        key=lambda v: float(v.get("compliance_score", v.get("final_score", 0)) or 0),
        reverse=True,
    )

    for idx, vendor in enumerate(sorted_vendors, start=1):
        score = vendor.get("compliance_score", vendor.get("final_score", 0))
        status_raw = str(vendor.get("status", vendor.get("pass_fail", "Rejected"))).lower()
        compliant = status_raw in {"eligible", "pass", "compliant", "true"}
        status = "Compliant" if compliant else "Rejected"
        rankings_data.append(
            [
                str(vendor.get("rank", idx)),
                str(vendor.get("vendor_name", vendor.get("name", "Unknown"))),
                str(score),
                status,
            ]
        )

    rankings_table = Table(rankings_data, colWidths=[20 * mm, 60 * mm, 35 * mm, 55 * mm])
    rankings_style = TableStyle(
        [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0B4F8A")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]
    )

    for row_idx in range(1, len(rankings_data)):
        row_color = colors.HexColor("#EAF3FF") if row_idx % 2 == 1 else colors.white
        rankings_style.add("BACKGROUND", (0, row_idx), (-1, row_idx), row_color)

    if len(rankings_data) > 1:
        rankings_style.add("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold")

    rankings_table.setStyle(rankings_style)
    story.append(rankings_table)
    story.append(Spacer(1, 8))

    # Section 3 - Compliance Details
    story.append(Paragraph("Section 3 — Compliance Details", section_style))
    if not sorted_vendors:
        story.append(Paragraph("No vendor compliance details available.", normal_style))
    else:
        for vendor in sorted_vendors:
            vendor_name = str(vendor.get("vendor_name", vendor.get("name", "Unknown")))
            vendor_score = vendor.get("compliance_score", vendor.get("final_score", 0))

            passed = _to_str_list(
                vendor.get("passed_criteria")
                or vendor.get("passed")
                or vendor.get("compliance_report", {}).get("passed_criteria")
            )
            failed = _to_str_list(
                vendor.get("failed_criteria")
                or vendor.get("failed")
                or vendor.get("compliance_report", {}).get("failed_criteria")
            )

            story.append(Paragraph(f"<b>{vendor_name}</b> - Score: {vendor_score}", normal_style))
            story.append(Paragraph(f"Passed criteria: {', '.join(passed) if passed else 'None'}", normal_style))
            story.append(Paragraph(f"Failed criteria: {', '.join(failed) if failed else 'None'}", normal_style))
            story.append(Spacer(1, 4))

    story.append(Spacer(1, 8))

    # Section 4 - Audit Trail Table
    story.append(Paragraph("Section 4 — Audit Trail Table", section_style))
    audit_data = [["Timestamp", "Event", "Performed By", "Details"]]

    for entry in audit_logs:
        if not isinstance(entry, dict):
            continue

        timestamp = entry.get("timestamp", "")
        if hasattr(timestamp, "isoformat"):
            timestamp = timestamp.isoformat()

        event = str(entry.get("event_type", ""))
        performed_by = str(entry.get("performed_by", "system"))
        details = entry.get("details", {})
        if isinstance(details, dict):
            details_str = ", ".join(f"{k}: {v}" for k, v in details.items())
        else:
            details_str = str(details)

        audit_data.append([str(timestamp), event, performed_by, details_str])

    if len(audit_data) == 1:
        audit_data.append(["-", "-", "-", "No audit logs available"])

    audit_table = Table(audit_data, colWidths=[38 * mm, 33 * mm, 28 * mm, 66 * mm], repeatRows=1)
    audit_style = TableStyle(
        [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0B4F8A")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
        ]
    )

    for row_idx in range(1, len(audit_data)):
        row_color = colors.HexColor("#EAF3FF") if row_idx % 2 == 1 else colors.white
        audit_style.add("BACKGROUND", (0, row_idx), (-1, row_idx), row_color)

    audit_table.setStyle(audit_style)
    story.append(audit_table)

    doc.build(story, canvasmaker=NumberedCanvas)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
